# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70e4572c698bd42fda604eb43d207b8d75a260dd9d1a110fc7e7777ea9cc97c03dd9cec83a24e4ad4ec119fae01aa89d74e2e5829f3ca55a5542a5878a046be

test:
  secret_key_base: 31d6372c74f5c294cff5751b62459b68b295191851d388539b832aba6cbb9f0bc1299b3ebd0e0a43f06cca3899e4555efb69ee99034c3dd171b156c13e8e8042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
